# Site settings
title: "James Clarke's photoblog"
email: your-email@domain.com
description: "James Clarke's photoblog"
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://localhost:4000" # the base hostname & protocol for your site
url: "http://www.greenandlonely.co.uk" # the base hostname & protocol for your site
twitter_username: greenandlonely
github_username: greenandlonely
permalink: /:title/

# Build settings
paginate: 3
paginate_path: /p/:num

//markdown: rdiscount
