# Gems
gems: [jekyll-paginate]

# Site settings
title: "James Clarke's photos"
email: jclarke0206@gmail.com
description: "James Clarke's photos"
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://localhost:4000" # the base hostname & protocol for your site
url: "http://www.greenandlonely.co.uk"
github_username: greenandlonely
permalink: /blog/:title/

# Build settings
paginate: 6
paginate_path: /blog/page:num

sass:
    style: :compressed

#markdown: rdiscount

exclude: [vendor]

