# Site settings
title: "James Clarke's photoblog"
email: jclarke0206@gmail.com
description: "James Clarke's photoblog, with infrequent words."
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://localhost:4000" # the base hostname & protocol for your site
url: "http://www.greenandlonely.co.uk"
github_username: greenandlonely
permalink: /:title/
# Build settings
paginate: 4
paginate_path: /page/:num

sass:
    style: :compressed

//markdown: rdiscount

