# Site settings
title: Green and lonely
email: your-email@domain.com
description: "A photo blog by James Clarke."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://localhost:4000" # the base hostname & protocol for your site
twitter_username: greenandlonely
github_username:  greenandlonely
permalink:    /:year/:month/:day/:title/

# Build settings
paginate: 10

markdown: rdiscount
